#pragma once

// version = (major << 16) + (minor << 8) + patch
#define ALIBABACLOUD_OSS_VERSION ((0 << 16) + (1 << 8) + 0)

#define ALIBABACLOUD_OSS_VERSION_STR "0.1.0"

// auto generated by cmake option
